// web/src/pages/ProjectBoard.tsx
import React, { useEffect, useState } from 'react';
import { Card, Table, Button, Modal, Form, Input, InputNumber, Select, Space, Tag, message, Spin, Drawer, Tabs, DatePicker, Divider } from 'antd';
import { PlusOutlined, ApartmentOutlined, MinusCircleOutlined, EditOutlined, SearchOutlined } from '@ant-design/icons';
import dayjs from 'dayjs';
import { getProjects, createProject, updateProject, getProject, getProjectDAG, addTask, updateTask } from '../services/api';
import type { Project, DAGData, Task } from '../types';

const ACCENT = '#2563eb';

const PROJECT_STATUS_LABELS: Record<string, string> = {
  active: '进行中',
  completed: '已完成',
  pending: '待启动',
  suspended: '已暂停',
  cancelled: '已取消',
  draft: '草稿',
};

const ProjectBoard: React.FC = () => {
  const [projects, setProjects] = useState<Project[]>([]);
  const [loading, setLoading] = useState(true);
  const [createOpen, setCreateOpen] = useState(false);
  const [detailOpen, setDetailOpen] = useState(false);
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);
  const [dagData, setDagData] = useState<DAGData | null>(null);
  const [taskOpen, setTaskOpen] = useState(false);
  const [editingTask, setEditingTask] = useState<Task | null>(null);
  const [filterCode, setFilterCode] = useState('');
  const [filterName, setFilterName] = useState('');
  const [filterClient, setFilterClient] = useState('');
  const [filterDateRange, setFilterDateRange] = useState<[dayjs.Dayjs | null, dayjs.Dayjs | null] | null>(null);
  const [editOpen, setEditOpen] = useState(false);
  const [createForm] = Form.useForm();
  const [editForm] = Form.useForm();
  const [taskForm] = Form.useForm();

  const fetchProjects = () => {
    setLoading(true);
    getProjects().then(setProjects).catch(() => message.error('加载项目失败')).finally(() => setLoading(false));
  };

  useEffect(() => { fetchProjects(); }, []);

  const handleCreate = async (values: Record<string, unknown>) => {
    const payload = {
      ...values,
      start_date: values.start_date ? dayjs(values.start_date as string).toISOString() : undefined,
      end_date: values.end_date ? dayjs(values.end_date as string).toISOString() : undefined,
    };
    await createProject(payload);
    message.success('项目创建成功');
    setCreateOpen(false);
    createForm.resetFields();
    fetchProjects();
  };

  const handleUpdateProject = async (values: Record<string, unknown>) => {
    if (!selectedProject) return;
    const payload = {
      ...values,
      start_date: values.start_date ? dayjs(values.start_date as string).toISOString() : undefined,
      end_date: values.end_date ? dayjs(values.end_date as string).toISOString() : undefined,
    };
    await updateProject(selectedProject.id, payload);
    message.success('项目更新成功');
    setEditOpen(false);
    fetchProjects();
    handleViewDetail(selectedProject.id);
  };

  const openEditProject = () => {
    if (!selectedProject) return;
    editForm.setFieldsValue({
      name: selectedProject.name,
      code: selectedProject.code,
      client_name: selectedProject.client_name,
      priority: selectedProject.priority,
      sla_level: selectedProject.sla_level,
      profit_weight: selectedProject.profit_weight,
      manager: selectedProject.manager,
      start_date: selectedProject.start_date ? dayjs(selectedProject.start_date) : null,
      end_date: selectedProject.end_date ? dayjs(selectedProject.end_date) : null,
    });
    setEditOpen(true);
  };

  const handleViewDetail = async (projId: number) => {
    const proj = await getProject(projId);
    const dag = await getProjectDAG(projId);
    setSelectedProject(proj);
    setDagData(dag);
    setDetailOpen(true);
  };

  const handleEditTask = (task: Task) => {
    setEditingTask(task);
    taskForm.setFieldsValue({
      name: task.name,
      task_type: task.task_type,
      est_duration_hours: task.est_duration_hours,
      switchover_hours: task.switchover_hours,
      predecessor_ids: task.predecessor_ids || [],
      capability_requirements: (task.capability_requirements || []).map((c) => ({
        tag_name: c.tag_name,
        tag_value: c.tag_value,
      })),
    });
    setTaskOpen(true);
  };

  const handleAddTask = async (values: Record<string, unknown>) => {
    if (!selectedProject) return;
    const payload = {
      ...values,
      requires_instrument: values.task_type === 'instrument',
      predecessor_ids: values.predecessor_ids || [],
      capability_requirements: (values.capability_requirements || []).map((c: Record<string, unknown>) => ({
        tag_name: c.tag_name,
        tag_value: c.tag_value,
      })),
    };
    if (editingTask) {
      await updateTask(editingTask.id, payload);
      message.success('任务更新成功');
    } else {
      await addTask(selectedProject.id, payload);
      message.success('任务添加成功');
    }
    setTaskOpen(false);
    setEditingTask(null);
    taskForm.resetFields();
    handleViewDetail(selectedProject.id);
  };

  const filteredProjects = projects.filter((p) => {
    if (filterCode && !p.code.toLowerCase().includes(filterCode.toLowerCase())) return false;
    if (filterName && !p.name.toLowerCase().includes(filterName.toLowerCase())) return false;
    if (filterClient && !(p.client_name || '').toLowerCase().includes(filterClient.toLowerCase())) return false;
    if (filterDateRange && filterDateRange[0] && filterDateRange[1]) {
      const start = filterDateRange[0].startOf('day');
      const end = filterDateRange[1].endOf('day');
      if (p.start_date) {
        const pStart = dayjs(p.start_date);
        if (pStart.isBefore(start) || pStart.isAfter(end)) return false;
      } else {
        return false;
      }
    }
    return true;
  });

  const columns = [
    { title: '项目编号', dataIndex: 'code', key: 'code', width: 130,
      render: (v: string) => <span style={{ fontFamily: 'monospace', fontWeight: 600, color: ACCENT, fontSize: 12 }}>{v}</span> },
    { title: '项目名称', dataIndex: 'name', key: 'name', ellipsis: true },
    { title: '客户', dataIndex: 'client_name', key: 'client', width: 140, ellipsis: true,
      render: (v: string) => v || '-' },
    { title: '负责人', dataIndex: 'manager', key: 'manager', width: 90,
      render: (v: string) => v || '-' },
    { title: '计划开始', dataIndex: 'start_date', key: 'start', width: 110,
      render: (v: string) => v ? dayjs(v).format('YYYY-MM-DD') : '-' },
    { title: '计划完成', dataIndex: 'end_date', key: 'end', width: 110,
      render: (v: string) => v ? dayjs(v).format('YYYY-MM-DD') : '-' },
    { title: '优先级', dataIndex: 'priority', key: 'priority', width: 80, align: 'center' as const,
      render: (v: number) => <Tag color={v >= 5 ? '#dc2626' : v >= 3 ? '#ea580c' : ACCENT}>{v}</Tag> },
    { title: '状态', dataIndex: 'status', key: 'status', width: 90,
      render: (v: string) => {
      const color = v === 'active' ? '#16a34a' : v === 'completed' ? '#7c3aed' : '#94a3b8';
      return <Tag color={color}>{PROJECT_STATUS_LABELS[v] || v}</Tag>;
    } },
    { title: '操作', key: 'actions', width: 130,
      render: (_: unknown, record: Project) => (
        <Space size={0}>
          <Button type="link" size="small" icon={<ApartmentOutlined />} onClick={() => handleViewDetail(record.id)}>详情</Button>
          <Button type="link" size="small" icon={<EditOutlined />} onClick={() => {
            setSelectedProject(record);
            editForm.setFieldsValue({
              name: record.name,
              code: record.code,
              client_name: record.client_name,
              priority: record.priority,
              sla_level: record.sla_level,
              profit_weight: record.profit_weight,
              start_date: record.start_date ? dayjs(record.start_date) : null,
              end_date: record.end_date ? dayjs(record.end_date) : null,
            });
            setEditOpen(true);
          }}>编辑</Button>
        </Space>
      )
    },
  ];

  return (
    <div>
      <div className="page-header">
        <h2>项目看板</h2>
        <p>管理项目、任务与依赖关系</p>
      </div>

      <div className="action-bar">
        <Button type="primary" icon={<PlusOutlined />} onClick={() => setCreateOpen(true)}>新建项目</Button>
        <Input
          placeholder="项目编号"
          prefix={<SearchOutlined />}
          allowClear
          style={{ width: 150 }}
          value={filterCode}
          onChange={(e) => setFilterCode(e.target.value)}
        />
        <Input
          placeholder="项目名称"
          prefix={<SearchOutlined />}
          allowClear
          style={{ width: 180 }}
          value={filterName}
          onChange={(e) => setFilterName(e.target.value)}
        />
        <Input
          placeholder="客户名称"
          prefix={<SearchOutlined />}
          allowClear
          style={{ width: 150 }}
          value={filterClient}
          onChange={(e) => setFilterClient(e.target.value)}
        />
        <DatePicker.RangePicker
          placeholder={['开始日期', '结束日期']}
          style={{ width: 240 }}
          value={filterDateRange as any}
          onChange={(dates) => setFilterDateRange(dates as any)}
          allowClear
        />
        <span style={{ marginLeft: 'auto', fontSize: 12, color: '#94a3b8', alignSelf: 'center' }}>
          {filteredProjects.length} / {projects.length} 个项目
        </span>
      </div>

      {loading ? <Spin size="large" style={{ display: 'block', margin: '50px auto' }} /> : (
        <Table dataSource={filteredProjects} columns={columns} rowKey="id" size="small" />
      )}

      {/* Create Project Modal */}
      <Modal title="新建项目" open={createOpen} onCancel={() => setCreateOpen(false)} onOk={() => createForm.submit()}
        width={640} okText="创建项目">
        <Form form={createForm} layout="vertical" onFinish={handleCreate}>
          <Form.Item name="name" label="项目名称" rules={[{ required: true, message: '请输入项目名称' }]}>
            <Input placeholder="如：某注射剂基因毒杂质研究" />
          </Form.Item>
          <Form.Item name="code" label="项目编号" rules={[{ required: true, message: '请输入项目编号' }]}>
            <Input placeholder="如：GT-2026-001" />
          </Form.Item>
          <Form.Item name="client_name" label="客户名称">
            <Input placeholder="如：某制药公司" />
          </Form.Item>
          <Form.Item name="manager" label="项目负责人">
            <Input placeholder="如：张三" />
          </Form.Item>
          <Space size={16}>
            <Form.Item name="priority" label="优先级" initialValue={3}>
              <InputNumber min={1} max={10} />
            </Form.Item>
            <Form.Item name="sla_level" label="SLA等级" initialValue="standard">
              <Select style={{ width: 120 }} options={[
                { label: '标准', value: 'standard' },
                { label: '加急', value: 'expedited' },
                { label: '特急', value: 'rush' },
              ]} />
            </Form.Item>
            <Form.Item name="profit_weight" label="利润权重" initialValue={1.0}>
              <InputNumber min={0.5} max={3} step={0.1} />
            </Form.Item>
          </Space>
          <Space size={16} style={{ width: '100%' }}>
            <Form.Item name="start_date" label="项目开始日期" style={{ width: 200 }}>
              <DatePicker placeholder="选择开始日期" style={{ width: '100%' }} />
            </Form.Item>
            <Form.Item name="end_date" label="项目结题日期" style={{ width: 200 }}>
              <DatePicker placeholder="选择结题日期" style={{ width: '100%' }} />
            </Form.Item>
          </Space>
        </Form>
      </Modal>

      {/* Edit Project Modal */}
      <Modal title="编辑项目" open={editOpen} onCancel={() => setEditOpen(false)} onOk={() => editForm.submit()}
        width={640} okText="保存">
        <Form form={editForm} layout="vertical" onFinish={handleUpdateProject}>
          <Form.Item name="name" label="项目名称" rules={[{ required: true, message: '请输入项目名称' }]}>
            <Input placeholder="如：某注射剂基因毒杂质研究" />
          </Form.Item>
          <Form.Item name="code" label="项目编号" rules={[{ required: true, message: '请输入项目编号' }]}>
            <Input placeholder="如：GT-2026-001" />
          </Form.Item>
          <Form.Item name="client_name" label="客户名称">
            <Input placeholder="如：某制药公司" />
          </Form.Item>
          <Form.Item name="manager" label="项目负责人">
            <Input placeholder="如：张三" />
          </Form.Item>
          <Space size={16}>
            <Form.Item name="priority" label="优先级" initialValue={3}>
              <InputNumber min={1} max={10} />
            </Form.Item>
            <Form.Item name="sla_level" label="SLA等级" initialValue="standard">
              <Select style={{ width: 120 }} options={[
                { label: '标准', value: 'standard' },
                { label: '加急', value: 'expedited' },
                { label: '特急', value: 'rush' },
              ]} />
            </Form.Item>
            <Form.Item name="profit_weight" label="利润权重" initialValue={1.0}>
              <InputNumber min={0.5} max={3} step={0.1} />
            </Form.Item>
          </Space>
          <Space size={16} style={{ width: '100%' }}>
            <Form.Item name="start_date" label="项目开始日期" style={{ width: 200 }}>
              <DatePicker placeholder="选择开始日期" style={{ width: '100%' }} />
            </Form.Item>
            <Form.Item name="end_date" label="项目结题日期" style={{ width: 200 }}>
              <DatePicker placeholder="选择结题日期" style={{ width: '100%' }} />
            </Form.Item>
          </Space>
        </Form>
      </Modal>

      {/* Project Detail Drawer */}
      <Drawer title={selectedProject?.name || '项目详情'} open={detailOpen} onClose={() => setDetailOpen(false)}
        extra={
          <Button icon={<EditOutlined />} onClick={openEditProject}>编辑项目</Button>
        }
        width={720}>
        {selectedProject && (
          <Tabs defaultActiveKey="tasks" items={[
            {
              key: 'tasks',
              label: '任务列表',
              children: (
                <div>
                  <div style={{ marginBottom: 12 }}>
                    <Button type="primary" icon={<PlusOutlined />} onClick={() => { setEditingTask(null); taskForm.resetFields(); setTaskOpen(true); }} size="small">
                      添加任务
                    </Button>
                  </div>
                  <Table dataSource={selectedProject.tasks || []} rowKey="id" size="small"
                    columns={[
                      { title: '任务名称', dataIndex: 'name', key: 'name' },
                      { title: '类型', dataIndex: 'task_type', key: 'type',
                        render: (v: string) => <Tag>{v === 'instrument' ? '仪器' : v === 'manual' ? '人工' : '等待'}</Tag> },
                      { title: '预计耗时(h)', dataIndex: 'est_duration_hours', key: 'dur' },
                      { title: '状态', dataIndex: 'status', key: 'status',
                        render: (v: string) => {
      const color = v === 'scheduled' ? '#7c3aed' : v === 'running' ? ACCENT : v === 'done' ? '#16a34a' : '#94a3b8';
      const label: Record<string, string> = { scheduled: '已排程', running: '运行中', done: '已完成', blocked: '阻塞', pending: '待处理' };
      return <Tag color={color}>{label[v] || v}</Tag>;
    } },
                      { title: '操作', key: 'actions', width: 60,
                        render: (_: unknown, record: Task) => (
                          <Button type="link" size="small" icon={<EditOutlined />} onClick={() => handleEditTask(record)} />
                        )
                      },
                    ]}
                    pagination={false} />
                </div>
              )
            },
            {
              key: 'dag',
              label: '依赖关系',
              children: (
                <div>
                  {dagData ? (
                    <div>
                      <div style={{ fontSize: 13, fontWeight: 600, color: '#334155', marginBottom: 8 }}>
                        任务节点 ({dagData.nodes.length})
                      </div>
                      {dagData.nodes.map(n => (
                        <Tag key={n.id} color={n.requires_instrument ? ACCENT : '#94a3b8'} style={{ margin: 4 }}>
                          {n.name} ({n.type})
                        </Tag>
                      ))}
                      {dagData.edges.length > 0 && (
                        <div style={{ marginTop: 16 }}>
                          <strong style={{ color: '#334155', fontSize: 13 }}>依赖关系：</strong>
                          {dagData.edges.map((e, i) => (
                            <div key={i} style={{ fontSize: 12, color: '#64748b', marginTop: 4 }}>
                              任务{e.from} → 任务{e.to}
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  ) : <Spin />}
                </div>
              )
            },
          ]} />
        )}
      </Drawer>

      {/* Add Task Modal */}
      <Modal title={editingTask ? '编辑任务' : '添加任务'} open={taskOpen} onCancel={() => { setTaskOpen(false); setEditingTask(null); }} onOk={() => taskForm.submit()}
        width={600} okText={editingTask ? '保存' : '添加任务'}>
        <Form form={taskForm} layout="vertical" onFinish={handleAddTask}
          initialValues={{ task_type: 'instrument', switchover_hours: 0.5, priority_weight: 1.0 }}>
          <Form.Item name="name" label="任务名称" rules={[{ required: true }]}>
            <Input placeholder="如：LC-MS方法开发" />
          </Form.Item>
          <Space style={{ width: '100%' }} size={16}>
            <Form.Item name="task_type" label="任务类型" initialValue="instrument">
              <Select style={{ width: 140 }} options={[
                { label: '仪器依赖型', value: 'instrument' },
                { label: '人工型', value: 'manual' },
                { label: '等待型', value: 'waiting' },
              ]} />
            </Form.Item>
            <Form.Item name="est_duration_hours" label="预计耗时(小时)" rules={[{ required: true, message: '必填' }]}>
              <InputNumber min={0.5} step={0.5} placeholder="如：8" style={{ width: 120 }} />
            </Form.Item>
            <Form.Item name="switchover_hours" label="切换时间(h)" initialValue={0.5}>
              <InputNumber min={0} step={0.5} style={{ width: 100 }} />
            </Form.Item>
          </Space>

          <Form.Item name="predecessor_ids" label="前置依赖任务">
            <Select mode="multiple" placeholder="选择依赖的前置任务（可选）"
              options={(selectedProject?.tasks || []).map(t => ({ label: t.name + ' (' + t.task_type + ')', value: t.id }))} />
          </Form.Item>

          <Divider style={{ margin: '12px 0' }}>仪器能力要求（仅仪器任务需要）</Divider>
          <Form.List name="capability_requirements">
            {(fields, { add, remove }) => (
              <>
                {fields.map(({ key, name, ...rest }) => (
                  <Space key={key} style={{ display: 'flex', marginBottom: 8 }} align="baseline">
                    <Form.Item {...rest} name={[name, 'tag_name']} rules={[{ required: true, message: '标签名' }]}>
                      <Select placeholder="能力标签" style={{ width: 140 }} options={[
                        { label: '离子源', value: '离子源' },
                        { label: '质量分析器', value: '质量分析器' },
                        { label: '方法类型', value: '方法类型' },
                        { label: '灵敏度等级', value: '灵敏度等级' },
                      ]} />
                    </Form.Item>
                    <Form.Item {...rest} name={[name, 'tag_value']} rules={[{ required: true, message: '值' }]}>
                      <Select placeholder="标签值" style={{ width: 160 }} options={[
                        { label: 'ESI', value: 'ESI' },
                        { label: 'APCI', value: 'APCI' },
                        { label: 'QqQ', value: 'QqQ' },
                        { label: 'Q-TOF', value: 'Q-TOF' },
                        { label: '基因毒杂质', value: '基因毒杂质' },
                        { label: '有关物质', value: '有关物质' },
                        { label: '含量测定', value: '含量测定' },
                        { label: '痕量', value: '痕量' },
                        { label: '常量', value: '常量' },
                      ]} />
                    </Form.Item>
                    <MinusCircleOutlined onClick={() => remove(name)} style={{ color: '#dc2626' }} />
                  </Space>
                ))}
                <Button type="dashed" onClick={() => add()} block icon={<PlusOutlined />}>
                  添加能力要求
                </Button>
              </>
            )}
          </Form.List>
        </Form>
      </Modal>
    </div>
  );
};

export default ProjectBoard;

// .pnpm-store/v11/projects/08248a9674c379edd003df36afa02f9f/src/pages/ProjectBoard.vue
<template>

  <div>

    <div class="page-header"><h2>项目看板</h2></div>

    <div class="action-bar">

      <a-button v-if="canManageProjectInfo" type="primary" @click="openCreate"><PlusOutlined /> 新建项目</a-button>

      <a-input placeholder="项目编号" allowClear style="width: 150px" v-model:value="filterCode"><template #prefix><SearchOutlined /></template></a-input>

      <a-input placeholder="项目名称" allowClear style="width: 180px" v-model:value="filterName"><template #prefix><SearchOutlined /></template></a-input>

      <a-input placeholder="客户名称" allowClear style="width: 150px" v-model:value="filterClient"><template #prefix><SearchOutlined /></template></a-input>

      <a-range-picker :placeholder="['开始日期','结束日期']" style="width: 240px" v-model:value="filterDateRange" allowClear />

      <span style="margin-left: auto; font-size: 12px; color: #94a3b8; align-self: center">{{ filtered.length }} / {{ projects.length }} 个项目</span>

    </div>

    <a-spin v-if="loading" size="large" style="display: block; margin: 50px auto" />

    <a-table v-else :dataSource="filtered" :columns="columns" rowKey="id" size="small" :pagination="{ pageSize: 20, showSizeChanger: true }">

      <template #bodyCell="{ column, record }">

        <template v-if="column.key === 'priority'">

          <a-tag :color="priorityColor(record.priority)">{{ priorityLabel(record.priority) }}</a-tag>

        </template>

        <template v-else-if="column.key === 'status'">

          <a-tag :color="projectStatusColor(record.status)">{{ statusLabels[record.status] || record.status }}</a-tag>

        </template>

        <template v-else-if="column.key === 'client'">{{ record.client_name || '-' }}</template>

        <template v-else-if="column.key === 'manager'">{{ record.manager_name || '-' }}</template>

        <template v-else-if="column.key === 'estimated_hours'">{{ record.estimated_hours ?? '-' }}</template>

        <template v-else-if="column.key === 'start'">{{ record.start_date ? dayjs(record.start_date).format('YYYY-MM-DD') : '-' }}</template>

        <template v-else-if="column.key === 'end'">{{ record.end_date ? dayjs(record.end_date).format('YYYY-MM-DD') : '-' }}</template>

        <template v-else-if="column.key === 'code'">

          <span style="font-family: monospace; font-weight: 600; color: #2563eb; font-size: 12px">{{ record.code }}</span>

        </template>

        <template v-else-if="column.key === 'actions'">

          <a-space :size="0">

            <a-button type="link" size="small" @click="handleViewDetail(record.id)">详情</a-button>

            <a-button v-if="canManageProjectInfo" type="link" size="small" @click="openEditFromTable(record)"><EditOutlined /> 编辑</a-button>

            <a-popconfirm title="确定删除该项目及其所有任务？" @confirm="handleDeleteProject(record.id)">

              <a-button type="link" size="small" danger>删除</a-button>

            </a-popconfirm>

          </a-space>

        </template>

      </template>

    </a-table>

    <a-modal title="新建项目" v-model:open="createOpen" @ok="handleCreate" width="640" okText="创建项目">

      <a-form layout="vertical">

        <a-form-item label="项目名称" required><a-input v-model:value="cf.name" placeholder="如：某注射剂基因毒杂质研究" /></a-form-item>

        <a-form-item label="项目编号" required><a-input v-model:value="cf.code" placeholder="如：GT-2026-001" /></a-form-item>

        <a-form-item label="客户名称"><a-input v-model:value="cf.client_name" placeholder="如：某制药公司" /></a-form-item>

        <a-form-item label="预计工时(小时)">
          <a-input-number v-model:value="cf.estimated_hours" :min="0" :step="0.5" style="width: 180px" placeholder="整个项目预计工时" />
        </a-form-item>

        <a-form-item label="项目负责人">
          <a-select v-model:value="cf.manager_id" placeholder="选择项目负责人" allowClear :options="userOptions" />
        </a-form-item>

        <a-form-item label="项目优先级">
          <a-select v-model:value="cf.priority" :options="priorityOptions" />
        </a-form-item>

        <a-space :size="16" style="width: 100%">

          <a-form-item label="项目开始日期" style="width: 200px"><a-date-picker v-model:value="cf.start_date" style="width: 100%" /></a-form-item>

          <a-form-item label="项目结题日期" style="width: 200px"><a-date-picker v-model:value="cf.end_date" style="width: 100%" /></a-form-item>

        </a-space>

      </a-form>

    </a-modal>

    <a-modal title="编辑项目" v-model:open="editOpen" @ok="handleUpdateProject" width="640" okText="保存">

      <a-form layout="vertical">

        <a-form-item label="项目名称" required><a-input v-model:value="ef.name" /></a-form-item>

        <a-form-item label="项目编号" required><a-input v-model:value="ef.code" /></a-form-item>

        <a-form-item label="客户名称"><a-input v-model:value="ef.client_name" /></a-form-item>

        <a-form-item label="预计工时(小时)">
          <a-input-number v-model:value="ef.estimated_hours" :min="0" :step="0.5" style="width: 180px" placeholder="整个项目预计工时" />
        </a-form-item>

        <a-form-item label="项目负责人">
          <a-select v-model:value="ef.manager_id" placeholder="选择项目负责人" allowClear :options="userOptions" />
        </a-form-item>

        <a-form-item label="项目优先级">
          <a-select v-model:value="ef.priority" :options="priorityOptions" />
        </a-form-item>

        <a-space :size="16" style="width: 100%">

          <a-form-item label="项目开始日期" style="width: 200px"><a-date-picker v-model:value="ef.start_date" style="width: 100%" /></a-form-item>

          <a-form-item label="项目结题日期" style="width: 200px"><a-date-picker v-model:value="ef.end_date" style="width: 100%" /></a-form-item>

        </a-space>

      </a-form>

    </a-modal>

    <a-drawer :title="selectedProject?.name || '项目详情'" v-model:open="detailOpen" width="720">

      <template #extra><a-button v-if="canManageProjectInfo" @click="openEditProject"><EditOutlined /> 编辑项目</a-button></template>

      <a-tabs v-if="selectedProject" defaultActiveKey="tasks">

        <a-tab-pane key="tasks" tab="任务列表">

          <a-descriptions size="small" bordered :column="2" style="margin-bottom: 12px">
            <a-descriptions-item label="项目编号">{{ selectedProject.code }}</a-descriptions-item>
            <a-descriptions-item label="状态">
              <a-tag :color="projectStatusColor(selectedProject.status)">{{ statusLabels[selectedProject.status] || selectedProject.status }}</a-tag>
            </a-descriptions-item>
            <a-descriptions-item label="客户">{{ selectedProject.client_name || '-' }}</a-descriptions-item>
            <a-descriptions-item label="负责人">{{ selectedProject.manager_name || '-' }}</a-descriptions-item>
            <a-descriptions-item label="预计工时(h)">{{ selectedProject.estimated_hours ?? '-' }}</a-descriptions-item>
            <a-descriptions-item label="优先级">{{ priorityLabel(selectedProject.priority) }}</a-descriptions-item>
            <a-descriptions-item label="项目开始日期">{{ selectedProject.start_date ? dayjs(selectedProject.start_date).format('YYYY-MM-DD') : '-' }}</a-descriptions-item>
            <a-descriptions-item label="项目结题日期">{{ selectedProject.end_date ? dayjs(selectedProject.end_date).format('YYYY-MM-DD') : '-' }}</a-descriptions-item>
          </a-descriptions>

          <a-table :dataSource="selectedProject.tasks || []" rowKey="id" size="small" :pagination="false">

            <a-table-column title="任务名称" dataIndex="name" key="name" />

            <a-table-column title="类型" key="type" width="90"><template #default="{ record }"><a-tag :color="getTaskTypeColor(record.task_type)" style="font-size:11px">{{ getTaskTypeName(record.task_type) }}</a-tag></template></a-table-column>

            <a-table-column title="预计耗时(h)" dataIndex="est_duration_hours" key="dur" width="100" />

            <a-table-column title="状态" key="status" width="80"><template #default="{ record }"><a-tag :color="taskStatusColor(record.status)" style="font-size:11px">{{ taskStatusLabel(record.status) }}</a-tag></template></a-table-column>

            <a-table-column title="负责人" key="assignee" width="80"><template #default="{ record }"><span style="font-size:12px;color:#475569">{{ record.assignee_name || "-" }}</span></template></a-table-column>

            <a-table-column title="操作" key="actions" width="60">

              <template #default="{ record }"><a-button type="link" size="small" @click="openEditTask(record)"><EditOutlined /></a-button></template>

            </a-table-column>

          </a-table>

          <a-button v-if="!isAddingTask" type="dashed" size="small" block @click="startAddTask" style="margin-top:8px"><PlusOutlined /> 添加任务</a-button>

          <div v-else style="margin-top:8px;padding:8px;background:#f8fafc;border-radius:6px;display:flex;align-items:center;gap:8px;flex-wrap:wrap">

            <a-input v-model:value="newTaskName" size="small" placeholder="任务名称" style="width:150px" />

            <a-select v-model:value="newTaskType" size="small" style="width:100px" :options="taskTypeOptions" placeholder="类型" />

            <a-input-number v-model:value="newTaskDuration" :min="0.5" :step="0.5" size="small" style="width:70px" addon-after='h' />

            <a-select v-model:value="newAssigneeId" size="small" style="width:110px" placeholder="负责人" allowClear :options="userOptions" />

            <a-button type="primary" size="small" @click="handleAddInline">确认</a-button>

            <a-button size="small" @click="cancelAddTask">取消</a-button>

          </div>

        </a-tab-pane>

        <a-tab-pane key="dag" tab="依赖关系">

          <div v-if="dagData">

            <div style="font-size: 13px; font-weight: 600; color: #334155; margin-bottom: 8px">任务节点 ({{ dagData.nodes.length }})</div>

            <a-tag v-for="n in dagData.nodes" :key="n.id" :color="n.requires_instrument ? '#2563eb' : '#94a3b8'" style="margin: 4px">{{ n.name }} ({{ n.type }})</a-tag>

            <div v-if="dagData.edges.length" style="margin-top: 16px">

              <strong style="color: #334155; font-size: 13px">依赖关系：</strong>

              <div v-for="(e,i) in dagData.edges" :key="i" style="font-size: 12px; color: #64748b; margin-top: 4px">任务{{ e.from }} -> 任务{{ e.to }}</div>

            </div>

          </div>

          <a-spin v-else />

        </a-tab-pane>

      </a-tabs>

    </a-drawer>

    <a-modal :title="editingTask ? '编辑任务' : '添加任务'" v-model:open="taskOpen" @ok="handleTaskSubmit" width="600" :okText="editingTask ? '保存' : '添加任务'">

      <a-form layout="vertical">

        <a-form-item label="任务名称" required><a-input v-model:value="tf.name" placeholder="如：LC-MS方法开发" /></a-form-item>

        <a-space :size="16" style="width: 100%">

          <a-form-item label="负责人"><a-select v-model:value="tf.assignee_id" style="width:100%" placeholder="选择负责人" allowClear :options="userOptions" /></a-form-item>

        <a-form-item label="任务类型"><a-select v-model:value="tf.task_type" style="width: 160px" :options="taskTypeOptions" placeholder="选择任务类型" /></a-form-item>

          <a-form-item label="预计耗时(小时)" required><a-input-number v-model:value="tf.est_duration_hours" :min="0.5" :step="0.5" style="width: 120px" /></a-form-item>

          <a-form-item label="切换时间(h)"><a-input-number v-model:value="tf.switchover_hours" :min="0" :step="0.5" style="width: 100px" /></a-form-item>

        </a-space>

        <a-form-item label="前置依赖任务">

          <a-select mode="multiple" v-model:value="tf.predecessor_ids" placeholder="选择依赖的前置任务（可选）"

            :options="(selectedProject?.tasks || []).map(t => ({ label: t.name + ' (' + (taskTypeMap[t.task_type]?.name || t.task_type) + ')', value: t.id }))" />

        </a-form-item>

        <a-divider>指定仪器</a-divider>
        <a-form-item label="选择仪器">
          <a-select v-model:value="tf.instrument_ids" mode="multiple" placeholder="选择该任务所需的仪器（可多选）" :options="instrumentOptions" style="width: 100%" />
        </a-form-item>

      </a-form>

    </a-modal>

  </div>

</template>





<script setup lang="ts">

import { ref, computed, reactive, onMounted } from 'vue'

import { useRouter } from 'vue-router'

import { message } from 'ant-design-vue'

import { isAxiosError } from 'axios'

import { PlusOutlined, EditOutlined, SearchOutlined, DeleteOutlined } from '@ant-design/icons-vue'

import { getProjects, createProject, updateProject, deleteProject, getProject, getProjectDAG, addTask, updateTask, deleteTask, getUsers, getTaskTypes, getInstruments, generateSchedule, type Project, type Task, type DAGData, type TaskTypeConfig } from '@/services/api'

import dayjs from 'dayjs'



const projects = ref<Project[]>([])

const loading = ref(true)

const createOpen = ref(false)

const editOpen = ref(false)

const detailOpen = ref(false)

const taskOpen = ref(false)

const selectedProject = ref<Project | null>(null)

const editingTask = ref<Task | null>(null)

const isAddingTask = ref(false)

const newTaskName = ref("")

const newTaskType = ref("")

const newTaskDuration = ref(8)

const newAssigneeId = ref<number | null>(null)

const userOptions = ref<{ label: string; value: number }[]>([])

const instrumentOptions = ref<{ label: string; value: number }[]>([])

const taskTypeOptions = ref<{ label: string; value: string; resource_type: string }[]>([])

const taskTypeMap = ref<Record<string, TaskTypeConfig>>({})

const dagData = ref<DAGData | null>(null)

const filterCode = ref('')

const filterName = ref('')

const filterClient = ref('')

const projectCodeCollator = new Intl.Collator('zh-CN', { numeric: true, sensitivity: 'base' })

const filterDateRange = ref<any>(null)



const router = useRouter()

const PROJECT_INFO_WRITE_ROLES = new Set(['系统管理员', '项目管理员', '分析所所长'])

const canManageProjectInfo = computed(() => PROJECT_INFO_WRITE_ROLES.has(getStoredUserRole()))

const cf = reactive({ name: '', code: '', client_name: '', estimated_hours: null as number | null, manager_id: null as number | null, priority: 3, start_date: null as any, end_date: null as any })

const ef = reactive({ name: '', code: '', client_name: '', estimated_hours: null as number | null, manager_id: null as number | null, priority: 3, start_date: null as any, end_date: null as any })

const tf = reactive({ name: '', task_type: '', est_duration_hours: 8, switchover_hours: 0.5, predecessor_ids: [] as number[], instrument_ids: [] as number[], assignee_id: null as number | null })




const statusLabels: Record<string, string> = { active: '进行中', completed: '已完成', pending: '未开始', suspended: '已暂停', cancelled: '已取消', draft: '草稿' }
const priorityOptions = [
  { label: '一级（最高）', value: 1 },
  { label: '二级', value: 2 },
  { label: '三级', value: 3 },
]

function priorityLabel(priority: number) {
  return priorityOptions.find(option => option.value === priority)?.label || `${priority}级`
}

function priorityColor(priority: number) {
  if (priority === 1) return '#dc2626'
  if (priority === 2) return '#ea580c'
  return '#2563eb'
}

function projectStatusColor(status: string) {
  const colors: Record<string, string> = {
    pending: '#94a3b8',
    active: '#16a34a',
    completed: '#7c3aed',
    suspended: '#f59e0b',
    cancelled: '#64748b',
    draft: '#94a3b8',
  }
  return colors[status] || '#94a3b8'
}



const capValOpts: Record<string, { label: string; value: string }[]> = {

  '离子源': [{ label: 'ESI', value: 'ESI' }, { label: 'APCI', value: 'APCI' }],

  '质量分析器': [{ label: 'QqQ', value: 'QqQ' }, { label: 'Q-TOF', value: 'Q-TOF' }],

  '方法类型': [{ label: '基因毒杂质', value: '基因毒杂质' }, { label: '有关物质', value: '有关物质' }, { label: '含量测定', value: '含量测定' }],

  '灵敏度等级': [{ label: '痕量', value: '痕量' }, { label: '常量', value: '常量' }],

}



const filtered = computed(() => projects.value.filter(p => {

  if (filterCode.value && !p.code.toLowerCase().includes(filterCode.value.toLowerCase())) return false

  if (filterName.value && !p.name.toLowerCase().includes(filterName.value.toLowerCase())) return false

  if (filterClient.value && !(p.client_name || '').toLowerCase().includes(filterClient.value.toLowerCase())) return false

  if (filterDateRange.value?.[0] && filterDateRange.value?.[1] && p.start_date) {

    const d = dayjs(p.start_date)

    if (d.isBefore(filterDateRange.value[0]) || d.isAfter(filterDateRange.value[1])) return false

  }

  return true

}).sort((left, right) =>
  projectCodeCollator.compare(right.code, left.code) || right.id - left.id,
))



const columns = [

  { title: '项目编号', dataIndex: 'code', key: 'code', width: 130 },

  { title: '项目名称', dataIndex: 'name', key: 'name', ellipsis: true },

  { title: '客户', dataIndex: 'client_name', key: 'client', width: 140 },

  { title: '负责人', dataIndex: 'manager', key: 'manager', width: 90 },

  { title: '预计工时(h)', dataIndex: 'estimated_hours', key: 'estimated_hours', width: 110 },

  { title: '计划开始', dataIndex: 'start_date', key: 'start', width: 110 },

  { title: '计划完成', dataIndex: 'end_date', key: 'end', width: 110 },

  { title: '优先级', dataIndex: 'priority', key: 'priority', width: 80 },

  { title: '状态', dataIndex: 'status', key: 'status', width: 90 },

  { title: '操作', key: 'actions', width: 200 },

]



async function fetchProjects() { loading.value = true; try { projects.value = await getProjects() } catch { message.error('加载项目失败') } finally { loading.value = false } }



function openCreate() {
  if (!ensureCanManageProjectInfo()) return
  Object.assign(cf, { name: '', code: '', client_name: '', estimated_hours: null, manager_id: null, priority: 3, start_date: null, end_date: null }); createOpen.value = true
}



async function handleCreate() {
  if (!ensureCanManageProjectInfo()) return

  try {

    await createProject({ ...cf, start_date: cf.start_date ? dayjs(cf.start_date).toISOString() : undefined, end_date: cf.end_date ? dayjs(cf.end_date).toISOString() : undefined } as any)

    message.success('项目创建成功'); createOpen.value = false; fetchProjects()

  } catch (error: unknown) { message.error(errorDetail(error, '创建失败')) }

}



async function handleUpdateProject() {

  if (!selectedProject.value) return
  if (!ensureCanManageProjectInfo()) return

  try {

    await updateProject(selectedProject.value.id, { ...ef, start_date: ef.start_date ? dayjs(ef.start_date).toISOString() : undefined, end_date: ef.end_date ? dayjs(ef.end_date).toISOString() : undefined } as any)

    message.success('项目更新成功'); editOpen.value = false; fetchProjects()

  } catch (error: unknown) { message.error(errorDetail(error, '更新失败')) }

}



function errorDetail(error: unknown, fallback: string) {
  if (isAxiosError<{ detail?: string }>(error)) return error.response?.data?.detail || fallback
  return fallback
}

function ensureCanManageProjectInfo() {
  if (canManageProjectInfo.value) return true
  message.warning('当前角色无权新建或编辑项目信息')
  return false
}

function getStoredUserRole() {
  const raw = localStorage.getItem('user')
  if (!raw) return ''
  try {
    const parsed = JSON.parse(raw) as { role?: unknown }
    return typeof parsed.role === 'string' ? parsed.role : ''
  } catch {
    return ''
  }
}

function handleViewDetail(id: number) {

  router.push(`/projects/plan-breakdown?id=${id}`)

}



function openEditFromTable(record: Project) { selectedProject.value = record; openEditProject() }



function openEditProject() {

  if (!selectedProject.value) return
  if (!ensureCanManageProjectInfo()) return

  const p = selectedProject.value

  Object.assign(ef, { name: p.name, code: p.code, client_name: p.client_name || '', estimated_hours: p.estimated_hours ?? null, manager_id: p.manager_id || null, priority: p.priority, start_date: p.start_date ? dayjs(p.start_date) : null, end_date: p.end_date ? dayjs(p.end_date) : null })

  editOpen.value = true

}





const taskList = computed(() => {

  const tasks = [...(selectedProject.value?.tasks || [])]

  if (isAddingTask.value) {

    tasks.push({ _isNew: true, id: -1 } as any)

  }

  return tasks

})



function taskStatusColor(s: string) {

  const m: Record<string, string> = { pending: '#94a3b8', running: '#2563eb', done: '#16a34a', blocked: '#dc2626', scheduled: '#ea580c' }

  return m[s] || '#94a3b8'

}



function taskStatusLabel(s: string) {

  const m: Record<string, string> = { pending: '待开始', running: '运行中', done: '已完成', blocked: '已延期', scheduled: '已排程' }

  return m[s] || s

}



function getTaskTypeName(code: string) { return taskTypeMap.value[code]?.name || code }

function getTaskTypeColor(code: string) { const r = taskTypeMap.value[code]?.resource_type; return r === "instrument" ? "#2563eb" : r === "human" ? "#16a34a" : "#7c3aed" }



function startAddTask() { isAddingTask.value = true; newTaskName.value = ''; newTaskType.value = 'instrument'; newTaskDuration.value = 8; newAssigneeId.value = null }



function cancelAddTask() { isAddingTask.value = false }



async function handleAddInline() {

  if (!newTaskName.value || !selectedProject.value) { message.error('请输入任务名称'); return }

  try {

    await addTask(selectedProject.value.id, {

      name: newTaskName.value,

      task_type: newTaskType.value,

      requires_instrument: (taskTypeMap.value[newTaskType.value]?.resource_type || 'both') !== 'human',

      est_duration_hours: newTaskDuration.value,

      switchover_hours: 0.5,

      predecessor_ids: [],

      assignee_id: newAssigneeId.value || null,

      instrument_ids: [],

    } as any)

    message.success('任务添加成功')

    isAddingTask.value = false

    const [p, d] = await Promise.all([getProject(selectedProject.value.id), getProjectDAG(selectedProject.value.id)])

    selectedProject.value = p; dagData.value = d

  } catch (error: unknown) { message.error(errorDetail(error, '添加失败')) }

}



async function handleDeleteProject(projId: number) {

  try {

    await deleteProject(projId)

    message.success('项目已删除')

    await fetchProjects()

    if (selectedProject.value?.id === projId) selectedProject.value = null

  } catch (e: any) {

    console.error('Delete project error:', e)

    const msg = e?.response?.data?.detail || e?.message || '删除失败'

    message.error(msg)

  }

}



async function handleDeleteTask(taskId: number) {

  if (!selectedProject.value) return

  try {

    await deleteTask(taskId)

    message.success('任务已删除')

    const [p, d] = await Promise.all([getProject(selectedProject.value.id), getProjectDAG(selectedProject.value.id)])

    selectedProject.value = p; dagData.value = d

  } catch { message.error('删除失败') }

}



function openAddTask() { editingTask.value = null; Object.assign(tf, { name: '', task_type: taskTypeOptions.value[0]?.value || '', est_duration_hours: 8, switchover_hours: 0.5, predecessor_ids: [],

      assignee_id: newAssigneeId.value || null, instrument_ids: [] }); taskOpen.value = true }



function openEditTask(t: Task) {

  editingTask.value = t

  Object.assign(tf, { name: t.name, task_type: t.task_type, est_duration_hours: t.est_duration_hours || 8, switchover_hours: t.switchover_hours, predecessor_ids: t.predecessor_ids || [], instrument_ids: t.instrument_ids || [], assignee_id: t.assignee_id || null })

  taskOpen.value = true

}



async function handleTaskSubmit() {

  if (!selectedProject.value) return

  const payload = {

    name: tf.name, task_type: tf.task_type,

    requires_instrument: (taskTypeMap.value[tf.task_type]?.resource_type || 'both') !== 'human',

    est_duration_hours: tf.est_duration_hours,

    switchover_hours: tf.switchover_hours,

    predecessor_ids: tf.predecessor_ids,

      assignee_id: tf.assignee_id || null,

    instrument_ids: tf.instrument_ids,

  }

  try {

    if (editingTask.value) {

      await updateTask(editingTask.value.id, payload as any)

      message.success('任务更新成功')

    } else {

      await addTask(selectedProject.value.id, payload as any)

      message.success('任务添加成功')

    }

    taskOpen.value = false; editingTask.value = null

    const [p, d] = await Promise.all([getProject(selectedProject.value.id), getProjectDAG(selectedProject.value.id)])

    selectedProject.value = p; dagData.value = d

  } catch (error: unknown) { message.error(errorDetail(error, '操作失败')) }

}



async function loadInstruments() {

  try {

    const insts = await getInstruments()

    instrumentOptions.value = insts.map(i => ({ label: i.name + ' (' + i.code + ')', value: i.id }))

  } catch (e) { console.error("loadInstruments failed:", e) }

}



async function loadUsers() {

  try {

    const users = await getUsers()

    userOptions.value = users.filter(u => u.is_active).map(u => ({ label: u.display_name, value: u.id }))

  } catch (e) { console.error("loadUsers failed:", e) }

}



async function loadTaskTypes() {

  try {

    const types = await getTaskTypes()

    const active = types.filter(t => t.is_active)

    taskTypeOptions.value = active.map(t => ({ label: t.name, value: t.code, resource_type: t.resource_type }))

    taskTypeMap.value = {}

    active.forEach(t => { taskTypeMap.value[t.code] = t })

    return active

  } catch (e) { console.error('loadTaskTypes failed:', e); return [] }

}



onMounted(async () => { await loadTaskTypes(); await Promise.all([fetchProjects(), loadUsers(), loadInstruments()]) })

</script>
