// web/src/pages/InstrumentGantt.vue
﻿<template>
  <div class="gantt-page">
    <div class="page-header"><h2>仪器甘特图</h2></div>

    <div class="action-bar">
      <a-button-group>
        <a-button :type="viewMode === 'day' ? 'primary' : 'default'" @click="switchView('day')">日</a-button>
        <a-button :type="viewMode === 'week' ? 'primary' : 'default'" @click="switchView('week')">周</a-button>
        <a-button :type="viewMode === 'month' ? 'primary' : 'default'" @click="switchView('month')">月</a-button>
      </a-button-group>
      <a-button @click="goPrev"><LeftOutlined /></a-button>
      <span style="font-weight: 600; min-width: 160px; text-align: center">{{ periodLabel }}</span>
      <a-button @click="goNext"><RightOutlined /></a-button>
      <a-button @click="goToday">今天</a-button>
      <a-button @click="fetchData"><ReloadOutlined /> 刷新</a-button>
      <span style="margin-left: auto; font-size: 12px; color: #94a3b8">{{ slots.length }} 个时间槽</span>
    </div>

    <a-spin v-if="loading" size="large" style="display: block; margin: 80px auto" />

    <div v-else-if="!instruments.length" style="padding: 80px; text-align: center; color: #94a3b8">
      暂无仪器数据，请先在「基础资源台账」中添加仪器并生成排程
    </div>

    <div v-else class="gantt-container" ref="containerRef">
      <div class="gantt-left" ref="leftRef">
        <div class="gantt-header-cell">仪器</div>
        <div v-for="row in flatRows" :key="'l-' + row.inst.id + '-q' + row.quarter"
          class="gantt-left-row" :class="{ 'is-subrow': row.isSubrow, 'is-last': row.isLast }"
          :style="{ height: Math.max(12, rowHeight) + 'px' }">
          <template v-if="!row.isSubrow || viewMode !== 'week'">
            <div class="inst-name">{{ row.inst.name }}</div>
            <div class="inst-code">{{ row.inst.code }}</div>
          </template>
        </div>
      </div>

      <div class="gantt-right" ref="rightRef" @scroll="onScroll">
        <div class="gantt-timeline-header" :style="{ width: totalWidth + 'px' }">
          <div v-for="col in timeColumns" :key="col.key" class="gantt-col-header" :style="{ width: colWidth + 'px' }"
            :class="{ 'is-weekend': col.isWeekend, 'is-today': col.isToday }">
            <div class="col-label-primary">{{ col.label }}</div>
            <div v-if="col.subLabel" class="col-label-sub">{{ col.subLabel }}</div>
          </div>
        </div>
        <div class="gantt-timeline-body" :style="{ width: totalWidth + 'px' }">
          <div v-for="row in flatRows" :key="'r-' + row.inst.id + '-q' + row.quarter"
            class="gantt-entity-row" :class="{ 'is-subrow': row.isSubrow, 'is-last': row.isLast }"
            :style="{ height: Math.max(12, rowHeight) + 'px' }">
            <div v-for="col in timeColumns" :key="col.key" class="gantt-grid-cell"
              :style="{ width: colWidth + 'px' }" :class="{ 'is-weekend': col.isWeekend, 'is-today': col.isToday }" />
            <div v-for="slot in getSlotsForQuarter(row.inst.id, row.quarter)" :key="slot.id"
              class="gantt-bar" :class="'status-' + slot.status"
              :style="getBarStyle(slot, row.quarter)"
              @mouseenter="e => showTooltip(slot, e)"
              @mouseleave="hideTooltip">
              <span class="bar-tag">{{ getProcessTag(slot.task_type) }}</span><span class="bar-label">{{ slot.task_name }}</span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div v-if="hoveredSlot" class="gantt-tooltip" :style="tooltipStyle">
      <div class="tooltip-title">{{ hoveredSlot.task_name }}</div>
      <div class="tooltip-row"><span>工序</span>{{ getTaskTypeLabel(hoveredSlot.task_type) }}</div>
      <div class="tooltip-row"><span>项目</span>{{ hoveredSlot.project_name }}</div>
      <div class="tooltip-row"><span>负责人</span>{{ hoveredSlot.assignee_name || '-' }}</div>
      <div class="tooltip-row"><span>开始</span>{{ dayjs(hoveredSlot.plan_start).format('MM-DD HH:mm') }}</div>
      <div class="tooltip-row"><span>结束</span>{{ dayjs(hoveredSlot.plan_end).format('MM-DD HH:mm') }}</div>
      <div class="tooltip-row"><span>状态</span>{{ statusLabel(hoveredSlot.status) }}</div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, nextTick } from 'vue'
import { message } from 'ant-design-vue'
import { LeftOutlined, RightOutlined, ReloadOutlined } from '@ant-design/icons-vue'
import { getInstruments, getTimeslots, getTaskTypes, type TaskTypeConfig } from '@/services/api'
import type { Instrument, TimeSlot } from '@/types'
import dayjs from 'dayjs'

const loading = ref(true)
const instruments = ref<Instrument[]>([])
const slots = ref<TimeSlot[]>([])
const viewMode = ref<'day' | 'week' | 'month'>('week')
const cursorDate = ref(dayjs().startOf('week'))
const hoveredSlot = ref<TimeSlot | null>(null)
const tooltipX = ref(0)
const tooltipY = ref(0)
const tooltipStyle = computed(() => ({ left: tooltipX.value + 'px', top: tooltipY.value + 'px' }))
const containerRef = ref<HTMLElement | null>(null)
const leftRef = ref<HTMLElement | null>(null)
const rightRef = ref<HTMLElement | null>(null)
const colWidth = ref(140)
const rowHeight = ref(200)
const taskTypeMap = ref<Record<string, string>>({})
const laneMap = ref<Record<number, Record<number, number>>>({})
const laneCounts = ref<Record<number, number>>({})

const flatRows = computed(() => {
  const rows: { inst: Instrument; quarter: number; isSubrow: boolean; isLast: boolean }[] = []
  for (const inst of instruments.value) {
    const qCount = viewMode.value === 'week' ? 4 : 1
    for (let q = 0; q < qCount; q++) {
      rows.push({ inst, quarter: q, isSubrow: viewMode.value === 'week' && q > 0, isLast: q === qCount - 1 })
    }
  }
  return rows
})

const totalWidth = computed(() => colWidth.value * timeColumns.value.length)

const periodLabel = computed(() => {
  const start = cursorDate.value
  if (viewMode.value === 'day') return start.format('YYYY年MM月DD日')
  if (viewMode.value === 'week') {
    const end = start.add(6, 'day')
    return `${start.format('MM/DD')} - ${end.format('MM/DD')}`
  }
  return start.format('YYYY年MM月')
})

interface TimeCol {
  key: string; label: string; subLabel: string; isWeekend: boolean; isToday: boolean
  start: dayjs.Dayjs; end: dayjs.Dayjs
}

const timeColumns = computed<TimeCol[]>(() => {
  const cols: TimeCol[] = []
  const today = dayjs().format('YYYY-MM-DD')
  if (viewMode.value === 'day') {
    for (let h = 0; h < 24; h++) {
      const d = cursorDate.value.hour(h)
      cols.push({
        key: 'h' + h, label: String(h).padStart(2, '0') + ':00', subLabel: '', isWeekend: false,
        isToday: d.format('YYYY-MM-DD') === today, start: d, end: d.add(1, 'hour')
      })
    }
  } else if (viewMode.value === 'week') {
    for (let i = 0; i < 7; i++) {
      const d = cursorDate.value.add(i, 'day')
      const dow = ['周日', '周一', '周二', '周三', '周四', '周五', '周六'][d.day()]
      cols.push({
        key: 'd' + i, label: dow, subLabel: d.format('MM/DD'),
        isWeekend: d.day() === 0 || d.day() === 6,
        isToday: d.format('YYYY-MM-DD') === today, start: d.startOf('day'), end: d.endOf('day')
      })
    }
  } else {
    const daysInMonth = cursorDate.value.daysInMonth()
    for (let i = 0; i < daysInMonth; i++) {
      const d = cursorDate.value.date(i + 1)
      const dow = ['日', '一', '二', '三', '四', '五', '六'][d.day()]
      cols.push({
        key: 'd' + i, label: (i + 1) + '日', subLabel: '周' + dow,
        isWeekend: d.day() === 0 || d.day() === 6,
        isToday: d.format('YYYY-MM-DD') === today, start: d.startOf('day'), end: d.endOf('day')
      })
    }
  }
  return cols
})

function computeLanes() {
  const map: Record<number, Record<number, number>> = {}
  const counts: Record<number, number> = {}
  for (const inst of instruments.value) {
    const instSlots = slots.value.filter(s => s.instrument_id === inst.id).sort((a, b) => dayjs(a.plan_start).valueOf() - dayjs(b.plan_start).valueOf())
    const lanes: { end: dayjs.Dayjs }[] = []
    const assign: Record<number, number> = {}
    for (const slot of instSlots) {
      const start = dayjs(slot.plan_start)
      let placed = false
      for (let i = 0; i < lanes.length; i++) {
        if (start.isAfter(lanes[i].end) || start.isSame(lanes[i].end)) {
          lanes[i].end = dayjs(slot.plan_end)
          assign[slot.id] = i
          placed = true
          break
        }
      }
      if (!placed) {
        assign[slot.id] = lanes.length
        lanes.push({ end: dayjs(slot.plan_end) })
      }
    }
    map[inst.id] = assign
    counts[inst.id] = Math.max(1, lanes.length)
  }
  laneMap.value = map
  laneCounts.value = counts
}

function getEntityRowStyle(_index: number, _quarter?: number) {
  return { height: Math.max(12, rowHeight.value) + 'px' }
}

function getLeftRowStyle(_index: number, _quarter?: number) {
  return { height: Math.max(12, rowHeight.value) + 'px' }
}

function getSlotsForQuarter(instId: number, quarter: number) {
  if (viewMode.value !== 'week') return getSlotsForInstrument(instId)
  const cols = timeColumns.value
  return getSlotsForInstrument(instId).filter(s => {
    const start = dayjs(s.plan_start)
    const end = dayjs(s.plan_end)
    for (const col of cols) {
      const dayStart = col.start
      const qStart = dayStart.hour(quarter * 6)
      const qEnd = dayStart.hour(quarter * 6 + 6)
      if (end.isAfter(qStart) && start.isBefore(qEnd)) return true
    }
    return false
  })
}

function getSlotsForInstrument(instId: number) {
  return slots.value.filter(s => s.instrument_id === instId)
}

function getBarStyle(slot: TimeSlot, quarter?: number) {
  const start = dayjs(slot.plan_start)
  const end = dayjs(slot.plan_end)
  const cols = timeColumns.value
  const cw = colWidth.value

  let startCol = -1, endCol = -1
  for (let i = 0; i < cols.length; i++) {
    if (startCol === -1 && end.isAfter(cols[i].start) && start.isBefore(cols[i].end)) startCol = i
    if (end.isAfter(cols[i].start) && start.isBefore(cols[i].end)) endCol = i
  }
  if (startCol === -1 || endCol === -1) return { display: 'none' }

  const colStart = cols[startCol].start
  const colDuration = cols[startCol].end.diff(colStart, 'second', true)
  const startOffset = Math.max(0, start.diff(colStart, 'second', true)) / Math.max(1, colDuration)

  const endColStart = cols[endCol].start
  const endColDuration = cols[endCol].end.diff(endColStart, 'second', true)
  const endOffset = Math.min(1, end.diff(endColStart, 'second', true) / Math.max(1, endColDuration))

  const left = (startCol + startOffset) * cw
  const right = (endCol + endOffset) * cw

  // In week view with quarters, position within the quarter sub-row
  if (viewMode.value === 'week' && quarter !== undefined) {
    let barStartCol = -1, barEndCol = -1
    for (let i = 0; i < cols.length; i++) {
      const dayStart = cols[i].start
      const qStart = dayStart.hour(quarter * 6)
      const qEnd = dayStart.hour(quarter * 6 + 6)
      if (end.isAfter(qStart) && start.isBefore(qEnd)) {
        if (barStartCol === -1) barStartCol = i
        barEndCol = i
      }
    }
    if (barStartCol === -1) return { display: 'none' }
    const firstDayStart = cols[barStartCol].start
    const firstQStart = firstDayStart.hour(quarter * 6)
    const firstQEnd = firstDayStart.hour(quarter * 6 + 6)
    const clampedStart = start.isBefore(firstQStart) ? firstQStart : start
    const firstOffset = clampedStart.diff(firstQStart, 'second', true) / 21600
    const lastDayStart = cols[barEndCol].start
    const lastQStart = lastDayStart.hour(quarter * 6)
    const lastQEnd = lastDayStart.hour(quarter * 6 + 6)
    const clampedEnd = end.isAfter(lastQEnd) ? lastQEnd : end
    const lastOffset = clampedEnd.diff(lastQStart, 'second', true) / 21600
    const barLeft = (barStartCol + firstOffset) * cw
    const barRight = (barEndCol + lastOffset) * cw
    return {
      left: barLeft + 'px',
      width: Math.max(3, barRight - barLeft) + 'px',
      top: '2px', bottom: '2px'
    }
  }
  
  const lane = (laneMap.value[slot.instrument_id] || {})[slot.id] || 0
  const laneCount = laneCounts.value[slot.instrument_id] || 1
  const laneH = Math.max(26, Math.floor((rowHeight.value - 4) / laneCount))
  const top = lane * laneH + 2

  return { left: left + 'px', width: Math.max(3, right - left) + 'px', top: top + 'px', height: (laneH - 2) + 'px' }
}

const processTags: Record<string, string> = { solution_prep: '溶', sample_prep: '前', instrument_run: '运', report: '审' }
function getProcessTag(code: string | undefined) { return code ? (processTags[code] || code.charAt(0)) : '' }
function getTaskTypeLabel(code: string | undefined) { return code ? (taskTypeMap.value[code] || code) : '' }

function statusLabel(s: string) {
  const m: Record<string, string> = { scheduled: '待处理', pending: '待处理', running: '运行中', completed: '已完成', blocked: '已延期', interrupted: '已延期' }
  return m[s] || s
}

function showTooltip(slot: TimeSlot, e: MouseEvent) {
  hoveredSlot.value = slot
  tooltipX.value = e.clientX + 12
  tooltipY.value = e.clientY - 100
}
function hideTooltip() { hoveredSlot.value = null }

function switchView(mode: 'day' | 'week' | 'month') {
  viewMode.value = mode
  if (mode === 'month') cursorDate.value = dayjs().startOf('month')
  else if (mode === 'week') cursorDate.value = dayjs().startOf('week')
  else cursorDate.value = dayjs().startOf('day')
  recalc()
  if (mode === 'day') scrollToNow()
}

function goPrev() {
  if (viewMode.value === 'day') cursorDate.value = cursorDate.value.subtract(1, 'day')
  else if (viewMode.value === 'week') cursorDate.value = cursorDate.value.subtract(1, 'week')
  else cursorDate.value = cursorDate.value.subtract(1, 'month')
}

function goNext() {
  if (viewMode.value === 'day') cursorDate.value = cursorDate.value.add(1, 'day')
  else if (viewMode.value === 'week') cursorDate.value = cursorDate.value.add(1, 'week')
  else cursorDate.value = cursorDate.value.add(1, 'month')
}

function goToday() {
  if (viewMode.value === 'month') cursorDate.value = dayjs().startOf('month')
  else if (viewMode.value === 'week') cursorDate.value = dayjs().startOf('week')
  else cursorDate.value = dayjs().startOf('day')
  recalc()
  if (viewMode.value === 'day') scrollToNow()
}

function onScroll() {
  if (leftRef.value && rightRef.value) leftRef.value.scrollTop = rightRef.value.scrollTop
}

function scrollToNow() {
  if (viewMode.value !== 'day' || !rightRef.value) return
  nextTick(() => {
    const hour = dayjs().hour()
    const containerH = rightRef.value.clientHeight
    rightRef.value.scrollTop = Math.max(0, hour * (rowHeight.value / 24) - containerH / 2)
  })
}

function recalc() {
  nextTick(() => {
    setTimeout(() => {
      if (!containerRef.value || containerRef.value.clientHeight <= 0) return
      computeLanes()
      const headerH = 50
      const availableH = containerRef.value.clientHeight - headerH - 2
      const entityCount = Math.max(1, instruments.value.length)
      const perEntity = Math.floor(availableH / entityCount)
      if (viewMode.value === 'week') {
        rowHeight.value = Math.floor(perEntity / 4)
      } else {
        rowHeight.value = perEntity
      }
      const available = containerRef.value.clientWidth - 160 - 2
      const cols = viewMode.value === 'day' ? 24 : viewMode.value === 'week' ? 7 : cursorDate.value.daysInMonth()
      colWidth.value = Math.max(60, available / cols)
    }, 50)
  })
}

async function fetchData() {
  loading.value = true
  try {
    const [insts, timeslots, types] = await Promise.all([getInstruments(), getTimeslots(), getTaskTypes()])
    instruments.value = insts
    slots.value = timeslots
    const map: Record<string, string> = {}
    types.forEach((t: TaskTypeConfig) => { map[t.code] = t.name })
    taskTypeMap.value = map
  } catch { message.error('加载数据失败') }
  finally {
    loading.value = false
    await nextTick()
    recalc()
    if (viewMode.value === 'day') scrollToNow()
  }
}

let resizeObserver: ResizeObserver | null = null

let refreshTimer: ReturnType<typeof setInterval> | null = null

onMounted(() => {
  fetchData()
  refreshTimer = setInterval(fetchData, 15000)
  window.addEventListener('resize', recalc)
  nextTick(() => {
    if (containerRef.value) {
      resizeObserver = new ResizeObserver(() => {
        if (containerRef.value && containerRef.value.clientHeight > 0) {
          recalc()
        }
      })
      resizeObserver.observe(containerRef.value)
    }
  })
})
onUnmounted(() => {
  if (refreshTimer) { clearInterval(refreshTimer); refreshTimer = null }
  window.removeEventListener('resize', recalc)
  if (resizeObserver) { resizeObserver.disconnect(); resizeObserver = null }
})
</script>

<style scoped>
.gantt-page { display: flex; flex-direction: column; height: calc(100vh - 64px); }

.gantt-container { display: flex; flex: 1; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden; margin-top: 12px; min-height: 0; }

.gantt-left { width: 160px; min-width: 160px; background: #f8fafc; border-right: 1px solid #e5e7eb; overflow-y: auto; overflow-x: hidden; }
.gantt-left::-webkit-scrollbar { width: 0; }
.gantt-header-cell { height: 50px; display: flex; align-items: center; padding: 0 12px; font-weight: 600; font-size: 13px; color: #475569; border-bottom: 2px solid #c0c7cf; background: #f1f5f9; }
.gantt-left-row { display: flex; flex-direction: column; justify-content: center; padding: 0 12px; border-bottom: none; overflow: hidden; }
.gantt-left-row.is-last { border-bottom: 2px solid #b0bec5; }
.inst-name { font-size: 13px; font-weight: 500; color: #1e293b; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.inst-code { font-size: 11px; color: #94a3b8; }

.gantt-right { flex: 1; overflow: auto; }
.gantt-right::-webkit-scrollbar { width: 6px; height: 6px; }
.gantt-right::-webkit-scrollbar-thumb { background: #cbd5e1; border-radius: 3px; }
.gantt-timeline-header { display: flex; height: 50px; border-bottom: 2px solid #c0c7cf; position: sticky; top: 0; background: #f1f5f9; z-index: 2; }
.gantt-col-header { display: flex; flex-direction: column; align-items: center; justify-content: center; border-right: 1px solid #c0c7cf; font-size: 12px; color: #64748b; flex-shrink: 0; box-sizing: border-box; }
.gantt-col-header.is-weekend { background: #fef2f2; }
.gantt-col-header.is-today { background: #dbeafe; }
.col-label-primary { font-weight: 600; font-size: 13px; }
.col-label-sub { font-size: 10px; color: #94a3b8; }

.gantt-timeline-body { position: relative; background: #fff; }
.gantt-entity-row { position: relative; display: flex; border-bottom: none; }
.gantt-entity-row.is-subrow { border-top: none; border-bottom: none; background: #fdfdfe; }
.gantt-entity-row.is-last { border-bottom: 2px solid #b0bec5; }
.gantt-entity-row.is-last .gantt-grid-cell { border-bottom: none; }
.gantt-entity-row.is-subrow:nth-child(even) { background: #f5f6f8; }
.gantt-entity-row:nth-child(even):not(.is-subrow) { background: #f8fafc; }
.gantt-grid-cell { border-right: 1px solid #c0c7cf; border-bottom: 1px solid #c0c7cf; flex-shrink: 0; box-sizing: border-box; }
.gantt-grid-cell.is-weekend { background: #fef2f2; }
.gantt-grid-cell.is-today { background: #eff6ff; }

.gantt-bar { position: absolute; border-radius: 3px; display: flex; align-items: center; padding: 0 5px; cursor: pointer; overflow: hidden; transition: box-shadow 0.15s; z-index: 1; box-sizing: border-box; gap: 3px; min-width: 0; box-shadow: 0 1px 2px rgba(0,0,0,0.06); }
.gantt-bar:hover { box-shadow: 0 2px 8px rgba(0,0,0,0.15); z-index: 3; }
.bar-tag { flex-shrink: 0; width: 18px; height: 18px; border-radius: 3px; display: flex; align-items: center; justify-content: center; font-size: 10px; font-weight: 700; background: rgba(0,0,0,0.12); color: inherit; }
.bar-label { font-size: 11px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; font-weight: 500; min-width: 0; color: inherit; }

/* Status colors */
.status-scheduled, .status-pending {
  background: #FF9800; color: #FFFFFF; border: 1px solid #F57C00;
  box-shadow: 0 2px 6px rgba(255, 152, 0, 0.3);
}
.status-running {
  background: #4CAF50; color: #FFFFFF; border: 1px solid #388E3C;
  box-shadow: 0 2px 6px rgba(76, 175, 80, 0.3);
}
.status-running::after {
  content: ""; position: absolute; left: 100%; top: 0; bottom: 0;
  width: 20px; background: #E8F5E9; border-radius: 0 3px 3px 0;
  pointer-events: none;
}
.status-completed {
  background: #2196F3; color: #FFFFFF; border: 1px solid #1976D2;
  box-shadow: 0 2px 6px rgba(33, 150, 243, 0.3);
}
.status-blocked, .status-interrupted {
  background: #E53935; color: #FFFFFF; border: 1px solid #C62828;
  box-shadow: 0 2px 6px rgba(229, 57, 53, 0.3);
}

.gantt-tooltip { position: fixed; background: #1e293b; color: #fff; padding: 12px 16px; border-radius: 8px; font-size: 12px; z-index: 1000; pointer-events: none; min-width: 180px; box-shadow: 0 4px 12px rgba(0,0,0,0.3); }
.tooltip-title { font-weight: 600; font-size: 13px; margin-bottom: 6px; }
.tooltip-row { display: flex; justify-content: space-between; padding: 2px 0; }
.tooltip-row span { color: #94a3b8; }
</style>

// web/src/pages/InstrumentGantt.tsx
import React, { useEffect, useState } from 'react';
import { Card, Select, Button, Space, Tag, Modal, Form, Input, InputNumber, message, Spin, Tabs, Tooltip } from 'antd';
import { PlusOutlined, PlayCircleOutlined, CheckCircleOutlined, CloseCircleOutlined, ReloadOutlined } from '@ant-design/icons';
import dayjs from 'dayjs';
import { getInstruments, getTimeslots, createInstrument, startTask, completeTask, interruptTask } from '../services/api';
import type { Instrument, TimeSlot } from '../types';

type ViewMode = 'day' | 'week' | 'month';

const ACCENT = '#2563eb';
const tierColors: Record<string, string> = { frozen: ACCENT, confirmed: '#16a34a', forecast: '#cbd5e1' };
const tierLabels: Record<string, string> = { frozen: '冻结', confirmed: '确认', forecast: '预测' };
const statusLabels: Record<string, string> = { scheduled: '待执行', running: '运行中', completed: '已完成', interrupted: '已中断' };

const SIDEBAR = 160;
const ROW_H = 68;
const HEADER_H = 38;

const InstrumentGantt: React.FC = () => {
  const [instruments, setInstruments] = useState<Instrument[]>([]);
  const [timeslots, setTimeslots] = useState<TimeSlot[]>([]);
  const [loading, setLoading] = useState(true);
  const [viewMode, setViewMode] = useState<ViewMode>('week');
  const [cursorDate, setCursorDate] = useState(dayjs());
  const [selectedInst, setSelectedInst] = useState<number[]>([]);
  const [addModalOpen, setAddModalOpen] = useState(false);
  const [detailSlot, setDetailSlot] = useState<TimeSlot | null>(null);
  const [addForm] = Form.useForm();

  const fetchData = () => {
    setLoading(true);
    const range = getDateRange();
    Promise.all([
      getInstruments(),
      getTimeslots({ start_date: range.start, end_date: range.end, ...(selectedInst.length > 0 ? { instrument_id: selectedInst[0] } : {}) })
    ]).then(([insts, slots]) => { setInstruments(insts); setTimeslots(slots); })
    .catch(() => message.error('加载数据失败'))
    .finally(() => setLoading(false));
  };

  useEffect(() => { fetchData(); }, [viewMode, cursorDate, selectedInst]);

  const getDateRange = () => {
    const s = cursorDate.startOf(viewMode === 'day' ? 'day' : viewMode === 'week' ? 'week' : 'month');
    const e = cursorDate.endOf(viewMode === 'day' ? 'day' : viewMode === 'week' ? 'week' : 'month');
    return { start: s.toISOString(), end: e.toISOString() };
  };

  const getColumns = (): { label: string; key: string; width: number; isWeekend?: boolean }[] => {
    if (viewMode === 'day') {
      const cols: { label: string; key: string; width: number }[] = [];
      for (let h = 0; h < 24; h++) cols.push({ label: h + ':00', key: 'h' + h, width: 60 });
      return cols;
    }
    if (viewMode === 'week') {
      const start = cursorDate.startOf('week');
      const days = ['一', '二', '三', '四', '五', '六', '日'];
      return days.map((d, i) => ({
        label: d + '\n' + start.add(i, 'day').format('MM/DD'),
        key: start.add(i, 'day').format('YYYY-MM-DD'),
        width: Math.floor((window.innerWidth - SIDEBAR - 80) / 7),
        isWeekend: i >= 5,
      }));
    }
    const start = cursorDate.startOf('month');
    const days = cursorDate.daysInMonth();
    const cols: { label: string; key: string; width: number; isWeekend?: boolean }[] = [];
    for (let d = 0; d < days; d++) {
      const date = start.add(d, 'day');
      cols.push({
        label: (d + 1).toString(),
        key: date.format('YYYY-MM-DD'),
        width: Math.floor((window.innerWidth - SIDEBAR - 80) / Math.min(days, 31)),
        isWeekend: [0, 6].includes(date.day()),
      });
    }
    return cols;
  };

  const getSlotStyle = (slot: TimeSlot, columns: { key: string; width: number }[]) => {
    const start = dayjs(slot.plan_start);
    const end = dayjs(slot.plan_end);
    if (viewMode === 'day') {
      const left = (start.hour() * 60 + start.minute()) / 60 * 60;
      const w = Math.max((end.diff(start, 'minute') / 60) * 60, 4);
      return { left, width: w };
    }
    const dateKey = start.format('YYYY-MM-DD');
    let left = 0;
    for (const col of columns) {
      if (col.key === dateKey) break;
      left += col.width;
    }
    const spanDays = Math.max(end.diff(start, 'day') + 1, 1);
    const colW = columns.find(c => c.key === dateKey)?.width || 60;
    return { left, width: Math.max(colW * spanDays, colW * 0.8) };
  };

  const navigate = (dir: -1 | 1) => {
    const unit = viewMode === 'day' ? 'day' : viewMode === 'week' ? 'week' : 'month';
    setCursorDate(cursorDate.add(dir, unit));
  };

  const titleStr = () => {
    if (viewMode === 'day') return cursorDate.format('YYYY年MM月DD日');
    if (viewMode === 'week') {
      const s = cursorDate.startOf('week');
      const e = cursorDate.endOf('week');
      return s.format('MM/DD') + ' - ' + e.format('MM/DD') + '  ' + cursorDate.format('YYYY年');
    }
    return cursorDate.format('YYYY年MM月');
  };

  const handleAddInstrument = async (values: any) => {
    await createInstrument(values);
    message.success('仪器添加成功');
    setAddModalOpen(false);
    addForm.resetFields();
    fetchData();
  };

  const handleTaskAction = async (slotId: number, action: string) => {
    try {
      if (action === 'start') await startTask(slotId);
      else if (action === 'complete') await completeTask(slotId);
      else if (action === 'interrupt') await interruptTask(slotId);
      message.success('操作成功');
      setDetailSlot(null);
      fetchData();
    } catch { message.error('操作失败'); }
  };

  const columns = getColumns();
  const filteredInsts = instruments.filter(i => selectedInst.length === 0 || selectedInst.includes(i.id));
  const totalWidth = columns.reduce((s, c) => s + c.width, 0);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: 'calc(100vh - 160px)' }}>
      <div style={{ marginBottom: 20 }}>
        <h2 style={{ margin: 0, fontSize: 20, fontWeight: 700, color: '#1e293b', letterSpacing: '-0.3px' }}>仪器甘特图</h2>
        <p style={{ margin: '4px 0 0', fontSize: 13, color: '#94a3b8' }}>日/周/月视图切换，拖拽缩放查看排程</p>
      </div>

      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12, flexWrap: 'wrap', gap: 8 }}>
        <Space wrap>
          <Select mode="multiple" placeholder="筛选仪器" style={{ minWidth: 200 }}
            value={selectedInst} onChange={setSelectedInst}
            options={instruments.map(i => ({ label: i.name, value: i.id }))} allowClear />
          <Button type="primary" icon={<PlusOutlined />} onClick={() => setAddModalOpen(true)}
            style={{ borderRadius: 8, fontWeight: 500 }}>添加仪器</Button>
          <Button icon={<ReloadOutlined />} onClick={fetchData} style={{ borderRadius: 8 }}>刷新</Button>
        </Space>
        <Space>
          {Object.entries(tierLabels).map(([k, v]) => (
            <Tag key={k} color={tierColors[k]} style={{
              color: k === 'forecast' ? '#475569' : '#fff',
              borderRadius: 5, border: 'none', fontWeight: 500,
            }}>{v}</Tag>
          ))}
        </Space>
      </div>

      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 0 }}>
        <Tabs activeKey={viewMode} onChange={(k) => setViewMode(k as ViewMode)}
          items={[
            { key: 'day', label: '日视图' },
            { key: 'week', label: '周视图' },
            { key: 'month', label: '月视图' },
          ]}
          style={{ marginBottom: 0 }}
        />
        <Space>
          <Button size="small" type="text" onClick={() => navigate(-1)} style={{ fontSize: 16 }}>{'<'}</Button>
          <span style={{ fontWeight: 600, fontSize: 14, color: '#334155', minWidth: 180, textAlign: 'center' }}>{titleStr()}</span>
          <Button size="small" type="text" onClick={() => navigate(1)} style={{ fontSize: 16 }}>{'>'}</Button>
          <Button size="small" onClick={() => setCursorDate(dayjs())} style={{ borderRadius: 6 }}>今天</Button>
        </Space>
      </div>

      {loading ? (
        <Spin size="large" style={{ display: 'block', margin: '100px auto' }} />
      ) : (
        <Card styles={{ body: { padding: 0, flex: 1, display: 'flex', flexDirection: 'column' } }}
          style={{ flex: 1, display: 'flex', overflow: 'hidden', borderRadius: 10, border: '1px solid #f1f5f9', boxShadow: 'none' }}>
          <div style={{ flex: 1, overflow: 'auto' }}>
            <div style={{ minWidth: SIDEBAR + totalWidth + 40 }}>
              <div style={{ display: 'flex', borderBottom: '1px solid #e2e8f0', background: '#f8fafc', height: HEADER_H, flexShrink: 0 }}>
                <div style={{ width: SIDEBAR, flexShrink: 0, display: 'flex', alignItems: 'center', padding: '0 14px', fontWeight: 600, fontSize: 12, color: '#64748b', borderRight: '1px solid #e2e8f0', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                  仪器
                </div>
                {columns.map(col => (
                  <div key={col.key} style={{
                    width: col.width, flexShrink: 0, display: 'flex', alignItems: 'center', justifyContent: 'center',
                    fontSize: 11, color: '#94a3b8', background: col.isWeekend ? '#f8fafc' : 'transparent',
                    borderRight: '1px solid #f1f5f9', whiteSpace: 'pre-line', textAlign: 'center', lineHeight: '14px', fontWeight: 500,
                  }}>
                    {col.label}
                  </div>
                ))}
              </div>

              {filteredInsts.length === 0 ? (
                <div style={{ padding: 60, textAlign: 'center', color: '#94a3b8', fontSize: 13 }}>暂无仪器，请先添加仪器</div>
              ) : (
                filteredInsts.map((inst, idx) => {
                  const instSlots = timeslots.filter(s => s.instrument_id === inst.id);
                  const isLast = idx === filteredInsts.length - 1;
                  return (
                    <div key={inst.id} style={{
                      display: 'flex', borderBottom: '1px solid #f1f5f9',
                      height: ROW_H, background: inst.status !== 'active' ? '#fef2f2' : (idx % 2 === 0 ? '#fff' : '#fafbfc'),
                      flex: isLast ? 1 : '0 0 auto'
                    }}>
                      <div style={{
                        width: SIDEBAR, flexShrink: 0, padding: '8px 14px', borderRight: '1px solid #e2e8f0',
                        background: '#f8fafc', display: 'flex', flexDirection: 'column', justifyContent: 'center'
                      }}>
                        <div style={{ fontWeight: 600, fontSize: 13, color: '#1e293b', lineHeight: '18px' }}>{inst.name}</div>
                        <div style={{ fontSize: 11, color: '#94a3b8', lineHeight: '16px' }}>{inst.brand} {inst.model}</div>
                        <Tag color={inst.status === 'active' ? '#16a34a' : '#dc2626'} style={{ fontSize: 10, marginTop: 2, lineHeight: '16px', borderRadius: 4, border: 'none' }}>
                          {inst.status === 'active' ? '正常' : inst.status}
                        </Tag>
                      </div>

                      <div style={{ position: 'relative', flex: 1 }}>
                        {columns.map(col => {
                          const colIdx = columns.indexOf(col);
                          const colLeft = columns.slice(0, colIdx).reduce((s, c) => s + c.width, 0);
                          return (
                            <div key={col.key} style={{
                              position: 'absolute', left: colLeft,
                              top: 0, width: col.width, height: '100%',
                              background: col.isWeekend ? '#fafbfc' : 'transparent',
                              borderRight: '1px solid #f8fafc'
                            }} />
                          );
                        })}

                        {instSlots.map(slot => {
                          const style = getSlotStyle(slot, columns);
                          const isRunning = slot.status === 'running';
                          const isCompleted = slot.status === 'completed';
                          const bg = tierColors[slot.tier] || tierColors.forecast;
                          return (
                            <Tooltip key={slot.id}
                              title={<div style={{ fontSize: 12 }}>
                                <div style={{ fontWeight: 600 }}>{slot.project_name}</div>
                                <div>{slot.task_name}</div>
                                <div style={{ color: '#94a3b8', marginTop: 4 }}>
                                  {dayjs(slot.plan_start).format('MM/DD HH:mm')} ~ {dayjs(slot.plan_end).format('HH:mm')}
                                </div>
                                <div style={{ marginTop: 2 }}>{statusLabels[slot.status]}</div>
                              </div>}
                            >
                              <div onClick={() => setDetailSlot(slot)} style={{
                                position: 'absolute', left: style.left, top: 6,
                                width: Math.max(style.width, 20), height: ROW_H - 12,
                                background: bg,
                                borderRadius: 5, color: slot.tier === 'forecast' ? '#475569' : '#fff',
                                fontSize: 11, padding: '4px 8px', overflow: 'hidden',
                                cursor: 'pointer', opacity: isCompleted ? 0.45 : 1,
                                border: isRunning ? '2px solid ' + ACCENT : '1px solid transparent',
                                boxShadow: isRunning ? '0 0 0 2px rgba(37,99,235,0.15)' : '0 1px 2px rgba(0,0,0,0.06)',
                                zIndex: isRunning ? 2 : 1,
                                display: 'flex', flexDirection: 'column', justifyContent: 'center',
                                lineHeight: '15px', minWidth: 0,
                                transition: 'box-shadow 0.15s',
                              }}>
                                <div style={{ fontWeight: 600, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                                  {slot.project_name}
                                </div>
                                <div style={{ whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', fontSize: 10, opacity: 0.85 }}>
                                  {slot.task_name}
                                </div>
                              </div>
                            </Tooltip>
                          );
                        })}
                      </div>
                    </div>
                  );
                })
              )}
            </div>
          </div>
        </Card>
      )}

      <Modal title="任务详情" open={!!detailSlot} onCancel={() => setDetailSlot(null)}
        footer={detailSlot ? [
          detailSlot.status === 'scheduled' && <Button key="start" type="primary" icon={<PlayCircleOutlined />} onClick={() => handleTaskAction(detailSlot.id, 'start')} style={{ borderRadius: 8 }}>开始执行</Button>,
          detailSlot.status === 'running' && <Button key="complete" type="primary" icon={<CheckCircleOutlined />} onClick={() => handleTaskAction(detailSlot.id, 'complete')} style={{ borderRadius: 8 }}>标记完成</Button>,
          detailSlot.status === 'running' && <Button key="interrupt" danger icon={<CloseCircleOutlined />} onClick={() => handleTaskAction(detailSlot.id, 'interrupt')} style={{ borderRadius: 8 }}>中断</Button>,
          <Button key="close" onClick={() => setDetailSlot(null)} style={{ borderRadius: 8 }}>关闭</Button>,
        ].filter(Boolean) : undefined}
      >
        {detailSlot && (
          <div>
            <p><strong>项目：</strong>{detailSlot.project_name}</p>
            <p><strong>任务：</strong>{detailSlot.task_name}</p>
            <p><strong>仪器：</strong>{detailSlot.instrument_name}</p>
            <p><strong>计划：</strong>{dayjs(detailSlot.plan_start).format('YYYY-MM-DD HH:mm')} ~ {dayjs(detailSlot.plan_end).format('HH:mm')}</p>
            <p><strong>层级：</strong><Tag color={detailSlot.tier === 'frozen' ? ACCENT : detailSlot.tier === 'confirmed' ? '#16a34a' : '#94a3b8'} style={{ borderRadius: 4, border: 'none' }}>{tierLabels[detailSlot.tier]}</Tag></p>
            <p><strong>状态：</strong><Tag color={detailSlot.status === 'completed' ? '#16a34a' : detailSlot.status === 'running' ? ACCENT : '#94a3b8'} style={{ borderRadius: 4, border: 'none' }}>{statusLabels[detailSlot.status]}</Tag></p>
            {detailSlot.actual_start && <p><strong>实际开始：</strong>{dayjs(detailSlot.actual_start).format('YYYY-MM-DD HH:mm')}</p>}
            {detailSlot.actual_end && <p><strong>实际结束：</strong>{dayjs(detailSlot.actual_end).format('YYYY-MM-DD HH:mm')}</p>}
          </div>
        )}
      </Modal>

      <Modal title="添加仪器" open={addModalOpen} onCancel={() => setAddModalOpen(false)} onOk={() => addForm.submit()}>
        <Form form={addForm} layout="vertical" onFinish={handleAddInstrument}>
          <Form.Item name="name" label="仪器名称" rules={[{ required: true }]}><Input /></Form.Item>
          <Form.Item name="brand" label="品牌"><Input /></Form.Item>
          <Form.Item name="model" label="型号"><Input /></Form.Item>
          <Form.Item name="location" label="位置"><Input /></Form.Item>
          <Form.Item name="buffer_rate" label="缓冲率" initialValue={0.85}><InputNumber min={0.5} max={1} step={0.05} /></Form.Item>
        </Form>
      </Modal>
    </div>
  );
};

export default InstrumentGantt;
