// web/src/pages/ProjectDAG.tsx
import React, { useEffect, useState, useMemo } from 'react';
import { Card, Select, Tag, Spin, Empty, message } from 'antd';
import { getProjects, getProjectDAG } from '../services/api';
import type { DAGData, Project } from '../types';

const ACCENT = '#2563eb';
const NODE_W = 180;
const NODE_H = 52;
const LAYER_GAP = 100;
const NODE_GAP = 24;

interface LayoutNode {
  id: number;
  name: string;
  type: string;
  requires_instrument: boolean;
  status: string;
  x: number;
  y: number;
  layer: number;
}

interface LayoutEdge {
  from: LayoutNode;
  to: LayoutNode;
}

const ProjectDAG: React.FC = () => {
  const [projects, setProjects] = useState<Project[]>([]);
  const [selectedProj, setSelectedProj] = useState<number | null>(null);
  const [dagData, setDagData] = useState<DAGData | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    getProjects().then(setProjects).catch(() => message.error('加载项目失败'));
  }, []);

  useEffect(() => {
    if (!selectedProj) { setDagData(null); return; }
    setLoading(true);
    getProjectDAG(selectedProj)
      .then(setDagData)
      .catch(() => message.error('加载依赖关系失败'))
      .finally(() => setLoading(false));
  }, [selectedProj]);

  const layout = useMemo(() => {
    if (!dagData || dagData.nodes.length === 0) return { nodes: [], edges: [], svgW: 0, svgH: 0 };

    const nodeMap = new Map(dagData.nodes.map(n => [n.id, n]));
    const children = new Map<number, number[]>();
    const parents = new Map<number, number[]>();
    dagData.nodes.forEach(n => { children.set(n.id, []); parents.set(n.id, []); });
    dagData.edges.forEach(e => {
      children.get(e.from)?.push(e.to);
      parents.get(e.to)?.push(e.from);
    });

    // Topological layering
    const layers: number[][] = [];
    const assigned = new Set<number>();
    const queue: number[] = [];
    dagData.nodes.forEach(n => { if ((parents.get(n.id)?.length || 0) === 0) queue.push(n.id); });

    while (queue.length > 0) {
      const currentLayer: number[] = [];
      const nextQueue: number[] = [];
      for (const nid of queue) {
        if (assigned.has(nid)) continue;
        currentLayer.push(nid);
        assigned.add(nid);
      }
      if (currentLayer.length === 0) break;
      layers.push(currentLayer);
      for (const nid of currentLayer) {
        for (const child of (children.get(nid) || [])) {
          if (!assigned.has(child)) nextQueue.push(child);
        }
      }
      queue.length = 0;
      queue.push(...nextQueue);
    }

    // Assign coordinates
    const layoutNodes: LayoutNode[] = [];
    layers.forEach((layer, li) => {
      const totalW = layer.length * NODE_W + (layer.length - 1) * NODE_GAP;
      const startX = -totalW / 2 + NODE_W / 2;
      layer.forEach((nid, ni) => {
        const node = nodeMap.get(nid)!;
        layoutNodes.push({
          id: node.id, name: node.name, type: node.type,
          requires_instrument: node.requires_instrument, status: node.status,
          x: startX + ni * (NODE_W + NODE_GAP),
          y: li * (NODE_H + LAYER_GAP) + NODE_H / 2,
          layer: li,
        });
      });
    });

    const nodeLookup = new Map(layoutNodes.map(n => [n.id, n]));
    const edges: LayoutEdge[] = dagData.edges
      .map(e => ({ from: nodeLookup.get(e.from)!, to: nodeLookup.get(e.to)! }))
      .filter(e => e.from && e.to);

    const maxX = Math.max(...layoutNodes.map(n => Math.abs(n.x) + NODE_W / 2), 400);
    const maxY = layers.length * (NODE_H + LAYER_GAP) + 40;

    return { nodes: layoutNodes, edges, svgW: maxX * 2 + 80, svgH: maxY };
  }, [dagData]);

  const statusColor = (status: string) => {
    switch (status) {
      case 'completed': return '#16a34a';
      case 'running': return ACCENT;
      case 'scheduled': return '#7c3aed';
      case 'blocked': return '#dc2626';
      default: return '#94a3b8';
    }
  };

  const statusLabel = (status: string) => {
    switch (status) {
      case 'completed': return '已完成';
      case 'running': return '运行中';
      case 'scheduled': return '已排程';
      case 'blocked': return '阻塞';
      default: return '待处理';
    }
  };

  return (
    <div>
      <div className="page-header">
        <h2>项目依赖关系</h2>
        <p>任务 DAG 拓扑图 — 可视化任务间的先后依赖与数据流</p>
      </div>

      <div style={{ marginBottom: 20 }}>
        <Select
          placeholder="选择项目查看依赖关系"
          style={{ width: 360 }}
          value={selectedProj}
          onChange={setSelectedProj}
          allowClear
          options={projects.map(p => ({ label: p.code + ' ' + p.name, value: p.id }))}
        />
      </div>

      {!selectedProj ? (
        <Card><Empty description="请先选择一个项目" /></Card>
      ) : loading ? (
        <Spin size="large" style={{ display: 'block', margin: '80px auto' }} />
      ) : !dagData || dagData.nodes.length === 0 ? (
        <Card><Empty description="该项目暂无任务" /></Card>
      ) : (
        <Card bodyStyle={{ padding: 0 }}>
          <div style={{
            overflow: 'auto',
            width: '100%',
            maxWidth: layout.svgW,
            minHeight: Math.max(layout.svgH, 300),
            background: '#fafbfc',
            position: 'relative',
          }}>
            <svg
              width={layout.svgW}
              height={layout.svgH}
              style={{ display: 'block' }}
            >
              <defs>
                <marker id="arrowhead" markerWidth="10" markerHeight="7" refX="10" refY="3.5" orient="auto">
                  <polygon points="0 0, 10 3.5, 0 7" fill="#cbd5e1" />
                </marker>
              </defs>

              {/* Edges */}
              {layout.edges.map((e, i) => {
                const fromX = e.from.x + layout.svgW / 2;
                const fromY = e.from.y;
                const toX = e.to.x + layout.svgW / 2;
                const toY = e.to.y;
                const midY = (fromY + toY) / 2;

                return (
                  <path
                    key={i}
                    d={`M ${fromX} ${fromY + NODE_H / 2} C ${fromX} ${midY}, ${toX} ${midY}, ${toX} ${toY - NODE_H / 2}`}
                    fill="none"
                    stroke="#cbd5e1"
                    strokeWidth={1.5}
                    markerEnd="url(#arrowhead)"
                  />
                );
              })}

              {/* Nodes */}
              {layout.nodes.map(n => {
                const cx = n.x + layout.svgW / 2;
                const cy = n.y;
                const isInstrument = n.requires_instrument;

                return (
                  <g key={n.id} transform={`translate(${cx - NODE_W / 2}, ${cy - NODE_H / 2})`}>
                    <rect
                      width={NODE_W}
                      height={NODE_H}
                      rx={8}
                      fill="#fff"
                      stroke={isInstrument ? ACCENT : '#e2e8f0'}
                      strokeWidth={isInstrument ? 1.5 : 1}
                      filter="url(#shadow)"
                    />
                    {/* Left accent bar for instrument tasks */}
                    {isInstrument && (
                      <rect x={0} y={0} width={4} height={NODE_H} rx={2} fill={ACCENT}
                        style={{ clipPath: 'inset(0 0 0 0 round 8px 0 0 8px)' }} />
                    )}
                    <text x={isInstrument ? 16 : 12} y={20} fontSize={12} fontWeight={600} fill="#1e293b"
                      textAnchor="start" dominantBaseline="middle"
                      style={{ maxWidth: NODE_W - 32 }}>
                      {n.name.length > 14 ? n.name.slice(0, 14) + '…' : n.name}
                    </text>
                    <text x={isInstrument ? 16 : 12} y={38} fontSize={11} fill="#94a3b8"
                      textAnchor="start" dominantBaseline="middle">
                      {n.type === 'instrument' ? '仪器任务' : n.type === 'manual' ? '人工任务' : '等待任务'}
                      {' · '}
                      <tspan fill={statusColor(n.status)}>{statusLabel(n.status)}</tspan>
                    </text>
                  </g>
                );
              })}
            </svg>
          </div>

          {/* Legend */}
          <div style={{
            padding: '12px 20px', borderTop: '1px solid #f1f5f9',
            display: 'flex', gap: 20, alignItems: 'center', flexWrap: 'wrap',
          }}>
            <span style={{ fontSize: 12, color: '#94a3b8', fontWeight: 500 }}>图例：</span>
            <span style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
              <span style={{ width: 12, height: 12, borderRadius: 3, border: '1.5px solid ' + ACCENT, background: '#fff' }} />
              <span style={{ fontSize: 12, color: '#475569' }}>仪器任务</span>
            </span>
            <span style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
              <span style={{ width: 12, height: 12, borderRadius: 3, border: '1px solid #e2e8f0', background: '#fff' }} />
              <span style={{ fontSize: 12, color: '#475569' }}>人工/等待任务</span>
            </span>
            <span style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
              <span style={{ width: 20, height: 2, background: '#cbd5e1' }} />
              <span style={{ fontSize: 12, color: '#475569' }}>前置依赖</span>
            </span>
            <span style={{ display: 'flex', alignItems: 'center', gap: 6, marginLeft: 8 }}>
              <Tag color={ACCENT} style={{ margin: 0, fontSize: 10 }}>运行中</Tag>
              <Tag color="#16a34a" style={{ margin: 0, fontSize: 10 }}>已完成</Tag>
              <Tag color="#7c3aed" style={{ margin: 0, fontSize: 10 }}>已排程</Tag>
              <Tag color="#94a3b8" style={{ margin: 0, fontSize: 10 }}>待处理</Tag>
            </span>
          </div>
        </Card>
      )}
    </div>
  );
};

export default ProjectDAG;

// web/src/pages/ProjectDAG.vue
<template>
  <div>
    <div class="page-header"><h2>项目依赖关系</h2><p>任务 DAG 拓扑图</p></div>
    <a-select placeholder="选择项目查看依赖关系" style="width: 360px; margin-bottom: 20px" v-model:value="selectedProj" allowClear
      :options="projects.map(p=>({label:p.code+' '+p.name,value:p.id}))" @change="loadDAG" />
    <a-spin v-if="loading" size="large" style="display: block; margin: 80px auto" />
    <a-empty v-else-if="!selectedProj" description="请选择一个项目查看依赖关系" />
    <a-card v-else-if="dagData">
      <div style="overflow: auto">
        <svg :width="svgW" :height="svgH" style="display: block">
          <defs><marker id="arrowhead" markerWidth="10" markerHeight="7" refX="10" refY="3.5" orient="auto"><polygon points="0 0, 10 3.5, 0 7" fill="#cbd5e1" /></marker></defs>
          <path v-for="(e,i) in layoutEdges" :key="i" :d="'M '+(e.from.x+svgW/2)+' '+(e.from.y+26)+' C '+(e.from.x+svgW/2)+' '+((e.from.y+e.to.y)/2)+', '+(e.to.x+svgW/2)+' '+((e.from.y+e.to.y)/2)+', '+(e.to.x+svgW/2)+' '+(e.to.y-26)" fill="none" stroke="#cbd5e1" strokeWidth="1.5" markerEnd="url(#arrowhead)" />
          <g v-for="n in layoutNodes" :key="n.id" :transform="'translate('+(n.x+svgW/2-90)+','+(n.y-26)+')'">
            <rect width="180" height="52" rx="8" fill="#fff" :stroke="n.requires_instrument?'#2563eb':'#e2e8f0'" :strokeWidth="n.requires_instrument?1.5:1" />
            <rect v-if="n.requires_instrument" x="0" y="0" width="4" height="52" rx="2" fill="#2563eb" />
            <text :x="n.requires_instrument?16:12" y="20" fontSize="12" fontWeight="600" fill="#1e293b">{{ n.name.length>14?n.name.slice(0,14)+'...':n.name }}</text>
            <text :x="n.requires_instrument?16:12" y="38" fontSize="11" fill="#94a3b8">{{ n.type==='instrument'?'仪器任务':n.type==='manual'?'人工任务':'等待任务' }} . <tspan :fill="statusColor(n.status)">{{ statusLabel(n.status) }}</tspan></text>
          </g>
        </svg>
      </div>
    </a-card>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from "vue"
import { message } from "ant-design-vue"
import { getProjects, getProjectDAG } from "@/services/api"
import type { Project, DAGData } from "@/types"

const NODE_W = 180; const NODE_H = 52; const LAYER_GAP = 100; const NODE_GAP = 24

const projects = ref<Project[]>([])
const selectedProj = ref<number | null>(null)
const dagData = ref<DAGData | null>(null)
const loading = ref(false)

interface LayoutNode { id: number; name: string; type: string; requires_instrument: boolean; status: string; x: number; y: number; layer: number }
interface LayoutEdge { from: LayoutNode; to: LayoutNode }

const layout = computed(() => {
  if (!dagData.value || !dagData.value.nodes.length) return { nodes: [], edges: [], svgW: 400, svgH: 200 }
  const nodes = dagData.value.nodes; const edges = dagData.value.edges
  const children = new Map<number, number[]>(); const parents = new Map<number, number[]>()
  nodes.forEach(n => { children.set(n.id, []); parents.set(n.id, []) })
  edges.forEach(e => { children.get(e.from)?.push(e.to); parents.get(e.to)?.push(e.from) })
  const layers: number[][] = []; const assigned = new Set<number>()
  let queue = nodes.filter(n => !parents.get(n.id)?.length).map(n => n.id)
  while (queue.length) {
    const layer: number[] = []
    queue.forEach(id => { if (!assigned.has(id)) { layer.push(id); assigned.add(id) } })
    if (!layer.length) break
    layers.push(layer)
    const next: number[] = []
    layer.forEach(id => children.get(id)?.forEach(c => { if (!assigned.has(c)) next.push(c) }))
    queue = next
  }
  const nodeMap = new Map(nodes.map(n => [n.id, n]))
  const layoutNodes: LayoutNode[] = []
  layers.forEach((layer, li) => {
    const tw = layer.length * NODE_W + (layer.length-1) * NODE_GAP
    const sx = -tw/2 + NODE_W/2
    layer.forEach((nid, ni) => {
      const n = nodeMap.get(nid)!
      layoutNodes.push({ id: n.id, name: n.name, type: n.type, requires_instrument: n.requires_instrument, status: n.status, x: sx + ni*(NODE_W+NODE_GAP), y: li*(NODE_H+LAYER_GAP)+NODE_H/2, layer: li })
    })
  })
  const nl = new Map(layoutNodes.map(n => [n.id, n]))
  const layoutEdges: LayoutEdge[] = edges.map(e => ({ from: nl.get(e.from)!, to: nl.get(e.to)! })).filter(e => e.from && e.to)
  const maxX = Math.max(...layoutNodes.map(n => Math.abs(n.x)+NODE_W/2), 400)
  const maxY = layers.length * (NODE_H+LAYER_GAP) + 40
  return { nodes: layoutNodes, edges: layoutEdges, svgW: maxX*2+80, svgH: maxY }
})

const layoutNodes = computed(() => layout.value.nodes)
const layoutEdges = computed(() => layout.value.edges)
const svgW = computed(() => layout.value.svgW)
const svgH = computed(() => layout.value.svgH)

function statusColor(s: string) { const m: Record<string,string>={completed:"#16a34a",running:"#2563eb",scheduled:"#7c3aed",blocked:"#dc2626"}; return m[s]||"#94a3b8" }
function statusLabel(s: string) { const m: Record<string,string>={completed:"已完成",running:"运行中",scheduled:"已排程",blocked:"阻塞"}; return m[s]||"待处理" }

onMounted(async () => { try { projects.value = await getProjects() } catch { message.error("加载项目失败") } })
async function loadDAG() { if(!selectedProj.value){dagData.value=null;return}; loading.value=true; try{dagData.value=await getProjectDAG(selectedProj.value)}catch{message.error("加载依赖关系失败")} finally{loading.value=false} }
</script>
